import { transform } from 'esbuild';
import { promises as fs } from 'node:fs';
import path from 'node:path';

const landingDir = path.resolve('ui_kits/landing');
const distDir = path.join(landingDir, 'dist');

const sources = [
  'Primitives.jsx',
  'CalendlyPopup.jsx',
  'Header.jsx',
  'Hero.jsx',
  'Services.jsx',
  'WhyUs.jsx',
  'HowItWorks.jsx',
  'Results.jsx',
  'Testimonials.jsx',
  'CTASection.jsx',
  'Footer.jsx',
  'App.jsx',
];

await fs.mkdir(distDir, { recursive: true });

for (const fileName of sources) {
  const inputPath = path.join(landingDir, fileName);
  const outPath = path.join(distDir, fileName.replace(/\.jsx$/i, '.js'));
  const input = await fs.readFile(inputPath, 'utf8');

  const result = await transform(input, {
    loader: 'jsx',
    jsx: 'transform',
    target: 'es2018',
    charset: 'utf8',
    sourcemap: false,
  });

  const banner = `/* AUTO-GENERATED by ui_kits/landing/build.mjs — DO NOT EDIT. Source: ${fileName} */\n`;
  await fs.writeFile(outPath, banner + result.code + '\n', 'utf8');
}

console.log(`Landing build complete: ${sources.length} files → ${path.relative(process.cwd(), distDir)}`);
